backend:
  name: github
  repo: hotpinkpoliticalmatrix/elevatedinfusions
media_folder: static/assets
branding_folder: src/images/branding
products_folder: src/content/products
public_folder: /assets
collections:
  - name: products
    label: Products
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
